cuenta/urls.py
from django.urls import path
from .views import profile, actualizar_perfil

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('update/', actualizar_perfil, name='update-profile')
]

sistemaERP/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('', include('administracion.urls')),
    path('gerente/', include('gerente.urls')),
    path('consultor/', include('consultor.urls')),
    path('procesos/', include('procesos.urls')),
    path('empleado/', include('empleado.urls')),
    path('resultado/', include('resultado.urls')),
    path('domicilio/', include('domicilio.urls')),
    path('cuenta/', include('cuenta.urls')),
    path('asistencia/', include('asistencia.urls')),
    # path('advanced_filters/', include('advanced_filters.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/models.py
from django.db import models
from domicilio.models import Zona,Locacion,Anexo
from administracion.models import Designacion
from procesos.models import Departmento

# Create your models here.
class EmpleadoDireccionInfo(models.Model):
    zona = models.ForeignKey(Zona, on_delete=models.CASCADE, null=True)
    locacion = models.ForeignKey(Locacion, on_delete=models.CASCADE, null=True)
    anexo = models.ForeignKey(Anexo, on_delete=models.CASCADE, null=True)
    cp = models.TextField()

    def __str__(self):
        return self.cp

class EducacionInfo(models.Model):
    nombre_de_evaluacion = models.CharField(max_length=100)
    instituto = models.CharField(max_length=255)
    grupo = models.CharField(max_length=100)
    grado = models.CharField(max_length=45)
    reunion = models.CharField(max_length=45)
    anio_presente = models.IntegerField()

    def __str__(self):
        return self.nombre_de_evaluacion

class EntrenamientoInfo(models.Model):
    nombre_entrenamiento = models.CharField(max_length=100)
    anio = models.IntegerField()
    duracion = models.IntegerField()
    lugar = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_entrenamiento

class EmpleadoTrabajoInfo(models.Model):
    eleccion_de_categoria = (
        ('bcs', 'BCS'),
        ('nacionalizado', 'nacionalizado'),
        ('cuota del 10%', 'cuota del 10%'),
        ('no gubernamental', 'no gubernamental')
    )
    categoria = models.CharField('Categoría',choices=eleccion_de_categoria, max_length=45)
    dia_de_ingreso = models.DateField('Día de ingreso')
    nombre_instituto = models.CharField('Nombre de Instituto',max_length=100)
    designacion_de_trabajo = models.ForeignKey(Designacion, on_delete=models.CASCADE)
    departmento = models.ForeignKey(Departmento, on_delete=models.CASCADE)
    escala = models.IntegerField('Escala')
    grado_publicacion = models.CharField('Grado de publicación',max_length=45)
    primer_periodo_de_contrato = models.IntegerField('Primer periodo de tiempo vencimiento de contrato')
    segundo_periodo_de_contrato = models.IntegerField('Segundo periodo de tiempo vencimiento de contrato')
    promocion_de_vencimiento = models.IntegerField('Promocion de vencimiento año/contrato')
    renovacion_contrato = models.IntegerField('Licencia de renovación por año/contrato')
    tiempo_jubilacion = models.IntegerField('Año jubilación esperado')


    def __str__(self):
        return self.nombre_instituto

class ExperienciaInfo(models.Model):
    nombre_instituto = models.CharField('Nombre del Instituto *',max_length=100)
    designation = models.CharField('Designación',max_length=45)
    entrenador = models.CharField('Capacitador',max_length=45)


    def __str__(self):
        return self.nombre_instituto

class PersonalInfo(models.Model):
    nombre = models.CharField('Nombre',max_length=45)
    foto = models.ImageField('Foto')
    fecha_nac = models.DateField('Fecha de nacimiento')
    lugar_nac = models.CharField('Lugar de nacimiento',max_length=45)
    eleccion_nacionalidad = (
        ('México', 'México'),
        ('Alemania', 'Alemania'),
        ('Rusia', 'Rusia'),
        ('Usa', 'Usa'),
        ('Otros', 'Otros')
    )
    nacionalidad = models.CharField('Nacionalidad',max_length=45, choices=eleccion_nacionalidad)
    eleccion_religion = (
        ('Islam', 'Islam'),
        ('Hinduismo', 'Hinduismo'),
        ('budismo', 'budismo'),
        ('cristianismo', 'cristianismo'),
        ('Otros', 'Otros')
    )
    religion = models.CharField('Religión',max_length=45, choices=eleccion_religion)
    eleccion_de_genero = (
        ('masculino', 'Masculino'),
        ('femenino', 'Femenino'),
        ('otro', 'Otro')
    )
    genero = models.CharField('Género',choices=eleccion_de_genero, max_length=10)
    eleccion_del_grupo_sanguineo = (
        ('a+', 'A+'),
        ('o+', 'O+'),
        ('b+', 'B+'),
        ('ab+', 'AB+'),
        ('a-', 'A-'),
        ('o-', 'O-'),
        ('b-', 'B-'),
        ('ab-', 'AB-')
    )
    grupo_sanguineo = models.CharField('Grupo sanguíneo',choices=eleccion_del_grupo_sanguineo, max_length=5)
    e_tin = models.IntegerField(unique=True)
    nid = models.IntegerField(unique=True)
    licencia_manejo_pasaporte = models.IntegerField('licencia de conducir/pasaporte',unique=True)
    numero_teleono = models.CharField('Número de telefono',max_length=11, unique=True)
    email = models.CharField(max_length=255, unique=True)
    nombre_padre = models.CharField('Nombre del Padre',max_length=45)
    nombre_madre = models.CharField('Nombre de la Madre',max_length=45)
    eleccion_de_estado_marital = (
        ('casado', 'Casado'),
        ('viudo', 'viudo'),
        ('separados', 'Separados'),
        ('divorciado', 'Divorciado'),
    )
    estado_marital = models.CharField('Estado Marital',choices=eleccion_de_estado_marital, max_length=10)
    direccion = models.ForeignKey(EmpleadoDireccionInfo, on_delete=models.CASCADE, null=True)
    educacion = models.ForeignKey(EducacionInfo, on_delete=models.CASCADE, null=True)
    capacitacion = models.ForeignKey(EntrenamientoInfo, on_delete=models.CASCADE, null=True)
    trabajo = models.ForeignKey(EmpleadoTrabajoInfo, on_delete=models.CASCADE, null=True)
    experiencia = models.ForeignKey(ExperienciaInfo, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.nombre

templates/gerente/gerente-edit.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Formulario de registro de Gerentes</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data" id="TeacherRegistrationForm" data-locacion-url={% url 'cargar-locacion' %}>

        <div class="card">
          <div class="card-header">Información personal</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Datos del Domicilio</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_direccion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información sobre Educación/Formación Academica/Experiencia</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_educacion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de entrenamiento</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_entrenamiento.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Informacion del trabajo</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_trabajo.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de la experiencia</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_experiencia.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_zona").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-locacion-url");
          var zonaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'zona': zonaId
            },
            success: function (data) {
              $("#id_locacion").html(data);
            }
          });

        });
        $("#id_locacion").change(function () {
         
          var url = $("#TeacherRegistrationForm").attr("data-locacion-url");
          var locacionId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'locacion': locacionId
            },
            success: function (data) {
              $("#id_anexo").html(data);
            }
          });

        });
      </script>
    </div>
  </div>
{% endblock %}

templates/gerente/gerente-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="animated fadeIn">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-edit"></i> Lista de Gerentes
          </div>
          {% if gerente %}
          <div class="card-body">
              <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="row">
                      <div class="col-sm-12 col-md-6">
                          <div class="dataTables_length" id="DataTables_Table_0_length">
                              <label>Mostrar
                                  <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="custom-select custom-select-sm form-control form-control-sm">
                                      <option value="10">10</option>
                                      <option value="25">25</option>
                                      <option value="50">50</option>
                                      <option value="100">100</option>
                                  </select> Entradas</label>
                          </div>
                      </div>
                      <div class="col-sm-12 col-md-6">
                          <div id="DataTables_Table_0_filter" class="dataTables_filter">
                              <label>Buscar:
                                  <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="DataTables_Table_0">
                              </label>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12">
                          <table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                              <thead>
                                  <tr role="row">
                                      <th>Id</th>
                                      <th>Nombre</th>
                                      <th>Género</th>
                                      <th>Nacionalidad</th>
                                      <th>Comportamiento</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {% for gerente in gerente %}
                                    <tr role="row" class="odd">
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ gerente.nombre }}</td>
                                        <td>{{ gerente.genero }}</td>
                                        <td>
                                            <span class="badge badge-warning">{{ gerente.nacionalidad }}</span>
                                        </td>
                                        <td>
                                            <a class="btn btn-success" href="{% url 'gerente-profile' gerente.id %}">
                                                <i class="fa fa-search-plus"></i>
                                            </a>
                                            <a class="btn btn-info" href="{% url 'gerente-edit' gerente.id %}">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-danger" href="{% url 'gerente-delete' gerente.id %}">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                  {% endfor %}
                              </tbody>
                          </table>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12 col-md-5">
                          <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 1 to 10 of 32 entries</div>
                      </div>
                      <div class="col-sm-12 col-md-7">
                          <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
                              <ul class="pagination">
                                  <li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
                                  <li class="paginate_button page-item active"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0" class="page-link">2</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                                  <li class="paginate_button page-item next" id="DataTables_Table_0_next"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="5" tabindex="0" class="page-link">Next</a></li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          {% else %}
          <div class="card-body">
              <h3>Ningún gerente encontrado</h3>
          </div>
          {% endif %}
      </div>
  </div>
{% endblock %}

templates/gerente/gerente-profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="card">
    <div class="card-header">
      <div class="row">
        <img style="height:200px; width:200px; border-radius:50%; margin:auto" src="{{ gerente.photo.url }}" alt="Photo">
      </div>
    </div>
    <div class="card-body">

      <div class="personal_information">
        <div class="row">
          <h2 class="mx-auto">Información Personal</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Nombre                             : {{ gerente.nombre }}</pre>
            <pre>Fecha de nacimiento                : {{ gerente.fecha_nac }}</pre>
            <pre>Lugar de nacimiento                : {{ gerente.lugar_nac }}</pre>
            <pre>Nacionalidad                       : {{ gerente.nacionalidad }}</pre>
            <pre>Religion                           : {{ gerente.religion }}</pre>
            <pre>Género                             : {{ gerente.genero }}</pre>
            <pre>Grupo sanguíneo                    : {{ gerente.grupo_sanguineo }}</pre>
            <pre>E-TIN                              : {{ gerente.e_tin }}</pre>
            <pre>Número de identificación nacional  : {{ gerente.nid }}</pre>
            <pre>Permiso de conducir/Pasaporte      : {{ gerente.licencia_manejo_pasaporte }}</pre>
            <pre>Número de Telefono                 : {{ gerente.numero_teleono }}</pre>
            <pre>Email                              : {{ gerente.email }}</pre>
            <pre>nombre_padre                       : {{ gerente.nombre_padre }}</pre>
            <pre>nombre_madre                       : {{ gerente.nombre_madre }}</pre>
            <pre>Estado Marital                     : {{ gerente.estado_marital }}</pre>
            <pre>Dirección                          : {{ gerente.direccion }}</pre>
            <pre>Educación                          : {{ gerente.educacion }}</pre>
            <pre>Capacitacion                       : {{ gerente.capacitacion }}</pre>
            <pre>Trabajo                            : {{ gerente.trabajo }}</pre>
            <pre>Expriencia                         : {{ gerente.experiencia }}</pre>
          </div>
        </div>
      </div>

      <div class="address_information">
        <div class="row">
          <h2 class="mx-auto">Datos del Domicilio</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Zona     : {{ gerente.direccion.zona }}</pre>
            <pre>Locacion : {{ gerente.direccion.locaion }}</pre>
            <pre>Anexo    : {{ gerente.direccion.anexo }}</pre>
            <pre>CP       : {{ gerente.direccion.cp }}</pre>
          </div>
        </div>
      </div>

      <div class="address_information">
        <div class="row">
          <h2 class="mx-auto">Información sobre Educación</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Nombre de Evaluación     : {{ gerente.educacion.nombre_de_evaluacion }}</pre>
            <pre>Instituto                : {{ gerente.educacion.instituto }}</pre>
            <pre>Grupo                    : {{ gerente.educacion.grupo }}</pre>
            <pre>Grado                    : {{ gerente.educacion.grado }}</pre>
            <pre>Consejo                  : {{ gerente.educacion.consejo }}</pre>
            <pre>periodo de aprobacion    : {{ gerente.educacion.periodo_de_aprobacion }}</pre>
          </div>
        </div>
      </div>

      <div class="emergency_contact_information">
        <div class="row">
          <h2 class="mx-auto">Información de entrenamiento</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Nombre de Entrenamiento  : {{ gerente.capacitacion.nombre_entrenamiento }}</pre>
            <pre>Año                      : {{ gerente.capacitacion.year }}</pre>
            <pre>Duracion                 : {{ gerente.capacitacion.duracion }}</pre>
            <pre>Lugar                    : {{ gerente.capacitacion.lugar }}</pre>
          </div>
        </div>
      </div>

      <div class="emergency_contact_information">
        <div class="row">
          <h2 class="mx-auto">Informacion del trabajo</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Categoría                      : {{ gerente.trabajo.categoria }}</pre>
            <pre>Día de ingreso                 : {{ gerente.trabajo.dia_de_ingreso }}</pre>
            <pre>Nombre instituto               : {{ gerente.trabajo.nombre_instituto }}</pre>
            <pre>Designacion de trabajo         : {{ gerente.trabajo.designacion_de_trabajo }}</pre>
            <pre>Departmento                    : {{ gerente.trabajo.departmento }}</pre>
            <pre>Escale                         : {{ gerente.trabajo.escala }}</pre>
            <pre>Grado Publicación              : {{ gerente.trabajo.grado_publicacion }}</pre>
            <pre>Primer Periodo de Contrato     : {{ gerente.trabajo.primer_periodo_de_contrato }}</pre>
            <pre>Promocion de Vencimiento       : {{ gerente.trabajo.promocion_de_vencimiento }}</pre>
            <pre>Renovacion Contrato            : {{ gerente.trabajo.renovacion_contrato }}</pre>
            <pre>Tiempo Jubilacion              : {{ gerente.trabajo.tiempo_jubilacion }}</pre>
          </div>
        </div>
      </div>

      <div class="previous_academic_information">
        <div class="row">
          <h2 class="mx-auto">Información de la experiencia</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Nombre Instituto : {{ gerente.experiencia.nombre_instituto }}</pre>
            <pre>Designación      : {{ gerente.experiencia.designation }}</pre>
            <pre>Entrenador       : {{ gerente.experiencia.entrenador }}</pre>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

templates/gerente/gerente-registration.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Formulario de registro de Gerentes</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data" id="TeacherRegistrationForm" data-loacion-url={% url 'cargar-locacion' %}>

        <div class="card">
          <div class="card-header">Información personal</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Datos del Domicilio</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_direccion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información sobre Educación/Formación Academica</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_educacion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de entrenamiento</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_entrenamiento.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Informacion del trabajo</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_trabajo.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de la experiencia</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_experiencia.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_zona").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-loacion-url");
          var zonaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'zona': zonaId
            },
            success: function (data) {
              $("#id_locacion").html(data);
            }
          });

        });
        $("#id_locacion").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-loacion-url");
          
          var locacionId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'locacion': locacionId
            },
            success: function (data) {
              $("#id_anexo").html(data);
            }
          });

        });
      </script>
    </div>
  </div>
{% endblock %}